global:
  scrape_interval: 5s
  scrape_timeout: 4s

rule_files:
  - /etc/prometheus/alerts.yaml

scrape_configs:
 - job_name: prometheus
   static_configs:
     - targets:
         - prometheus:9090
 - job_name: gateway
   metrics_path: /metrics
   static_configs:
     - targets:
         - gateway:8780
 - job_name: sglang
   metrics_path: /metrics
   static_configs:
     - targets:
         - worker-a:8000
       labels:
         worker: worker-a
     - targets:
         - worker-b:8000
       labels:
         worker: worker-b